### REALIZAR REGISTRO DE USUÁRIO
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
  "nomeUsuario": "Arthur Manager",
  "nome": "Arthur",
  "senha": "arthurFez",
  "email": "arthur.manager@gmail.com",
  "role": "MANAGER"
}

### REALIZAR LOGIN 
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
  "nomeUsuario": "Arthur Manager",
  "senha": "arthurFez"
}

### INSERIR PRODUTO SEM TOKEN VALIDO (Err)
POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json

{
  "nome": "Produto 101",
  "preco": 7.78,
  "emailEmpresa": "mail@mail.com",
  "dataValidade": "2025-06-14",
  "categoria": 1
}

### INSERIR CATEGORIA COM TOKEN VALIDO (Happy)
POST http://localhost:3000/categorias HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiQXJ0aHVyIE1hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc1MDI1NzE4OSwiZXhwIjoxNzUwMjYwNzg5fQ.6d56A0e1syDoqxzAEXcXgId8ymmr6o3HePtSUwNylF0

{
  "nome": "Frutas"
}

### INSERIR PRODUTO COM TOKEN VALIDO (Happy)
POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiQXJ0aHVyIE1hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc1MDI1NzE4OSwiZXhwIjoxNzUwMjYwNzg5fQ.6d56A0e1syDoqxzAEXcXgId8ymmr6o3HePtSUwNylF0

{
  "nome": "Banana",
  "preco": 5.99,
  "emailEmpresa": "vendedoraDeBananas@gmail.com",
  "dataValidade": "2025-06-14",
  "categoriaId": 1
}