###
### Produtos
###

### Listar todos os produtos
GET http://localhost:3000/produtos HTTP/1.1

### Listar produto específico por ID
GET http://localhost:3000/produtos/1 HTTP/1.1

### Criar novo produto
POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json

{
  "nome": "string",
  "preco": 10,
  "emailEmpresa": "teste@mail.com",
  "dataValidade": "2025-06-12"
}

### Atualizar produto (parcial)
PATCH http://localhost:3000/produtos/1 HTTP/1.1
Content-Type: application/json

{
  "nome": "Produto dois",
  "preco": 9
}

### Deletar produto
DELETE http://localhost:3000/produtos/1 HTTP/1.1


###
### Categorias
###

### Listar todas as categorias
GET http://localhost:3000/categorias HTTP/1.1

### Listar categoria por ID
GET http://localhost:3000/categorias/1 HTTP/1.1

### Criar nova categoria
POST http://localhost:3000/categorias HTTP/1.1
Content-Type: application/json

{
  "nome": "Categoria 10",
  "ativa": false
}

### Atualizar categoria (parcial)
PATCH http://localhost:3000/categorias/1 HTTP/1.1
Content-Type: application/json

{
  "nome": "Categoria 7",
  "ativa": true
}

### Deletar categoria
DELETE http://localhost:3000/categorias/2 HTTP/1.1


###
### Autenticação
###

### Registro de usuário
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nomeUsuario": "diego2",
  "nome": "Diego Rod2",
  "senha": "123456",
  "email": "diego2@mail.com"
}

### Login de usuário
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "nomeUsuario": "diego2",
  "senha": "123456"
}


###
### Testes com token
###

### Criar produto sem token (esperado erro)
POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json

{
  "nome": "Produto 101",
  "preco": 7.78,
  "emailEmpresa": "mail@mail.com",
  "dataValidade": "2025-06-14",
  "categoria": 1
}

### Criar produto com token válido
POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiZGllZ28yIiwiaWF0IjoxNzQ4NDUzNTg1LCJleHAiOjE3NDg0NTcxODV9.4S60JKDaKTLW6fBe785TnoU5uGwWHNGUGMkRhvx5R5s

{
  "nome": "Produto 101",
  "preco": 7.78,
  "emailEmpresa": "mail@mail.com",
  "dataValidade": "2025-06-14",
  "categoria": 1
}

### Editar produto com token válido
PATCH http://localhost:3000/produtos/10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiZGllZ28iLCJpYXQiOjE3NDcyNDgxMjgsImV4cCI6MTc0NzI1MTcyOH0.hBkwTM5WYlkJ9Oh0WgyjRNGAWxncup4Kq2uYnaI0EUE

{
  "nome": "Produto 88",
  "preco": 8.88
}

### Deletar produto com token válido
DELETE http://localhost:3000/produtos/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiZGllZ28iLCJpYXQiOjE3NDcyNDgxMjgsImV4cCI6MTc0NzI1MTcyOH0.hBkwTM5WYlkJ9Oh0WgyjRNGAWxncup4Kq2uYnaI0EUE
